cabal-version:      3.0
name:               matching-engine
version:            0.1.0.0
synopsis:           A price-time-priority limit order book matching engine
description:        A small, correctness-first central limit order book (CLOB)
                    matching engine.
license:            BSD-3-Clause
author:             mchaver
maintainer:         mchaver@gmail.com
build-type:         Simple

common warnings
    ghc-options: -Wall
                 -Wcompat
                 -Wincomplete-record-updates
                 -Wincomplete-uni-patterns
                 -Wredundant-constraints

library
    import:           warnings
    exposed-modules:  OrderBook.Types
                      OrderBook.Book
    build-depends:    base       >=4.17 && <5
                    , containers
    hs-source-dirs:   src
    default-language: GHC2021

executable matching-engine-demo
    import:           warnings
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base
                    , matching-engine
    default-language: GHC2021

test-suite spec
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   test
    build-depends:    base
                    , matching-engine
                    , hedgehog
    default-language: GHC2021
